name: Smarty Bucket Master Branch CI

on:
  pull_request:
    branches:
      - 'master'
      - 'staging' 
  push:
    branches:
      - 'master'
      - 'staging'

jobs:
        
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android sdkmanager
        run: |
          wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
          sudo unzip -d $ANDROID_HOME android-sdk.zip > /dev/null
      - name: Install required Android tools
        run: |
          echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "cmake;${ANDROID_CMAKE}" > /dev/null
          echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager --licenses > /dev/null
      - name: Build with Gradle
        run: |
          export PATH="$ANDROID_HOME/cmake/${ANDROID_CMAKE}/bin:$PATH"
          ./gradlew build
      - name: Install ndk
        run: sdkmanager 'ndk;20.0.5594570'
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
